[package]
name = "scorpion"
version = "0.1.0"
edition = "2021"
description = "Sequencing via Combinatorial Optimization for Rendezvous Planning and Intelligent Orbital Navigation"

[dependencies]
csv = "1.3"
serde = { version = "1", features = ["derive"] }
rand = { version = "0.8", features = ["small_rng"] }

[lib]
name = "scorpion"
path = "src/lib.rs"

[[bin]]
name = "scorpion"
path = "src/main.rs"
